### PR TITLE
Note title contrast color / updated build process

### PR DESCRIPTION
**Pull request by hibroseph**

### CODE REVIEW

**Comment by hibroseph** [comment]
#17 got em

**Comment by hibroseph** [comment]
This is an example of why you need to be sure where you are opening the pull request. Also **do not** branch off a branch. Always return to the main branch.

**Comment by adlythebaud** [comment]
Getting this when running npm run start on branch **note_title_contrast_color** 
image

**Comment by adlythebaud** [comment]
PR looks good. I followed the instructions in your README and it worked like a charm.
Only potential issue I see is figuring out if we should include files in the cache and package.json & package-lock.json in the gitignore...?

image

Otherwise, the PR looks great.

**Comment by hibroseph** [comment]
I don't believe we should ever commit any file with . since those are usually local files. I am going to add the package-lock.json. Apparently it has to do with your npm version? not too sure but someone said just commit so imma do it. I'll look more into it in the future

**Pull request merged**
